import img1 from '../components/image/img1.jpg'
import img2 from '../components/image/img2.jpg'
import img3 from '../components/image/img3.jpg'
import img4 from '../components/image/img4.jpg'
import img5 from '../components/image/img5.jpg'
import img6 from '../components/image/img6.jpg'

const data = {
    cardData: [
        {
            id: 1,
            img: img1,
            title: '12723 - Andhra Pradesh Express',
            desc: '	Hyderabad Decan to New Delhi',
            time: '06:25 - 09:25',
            classes: '1A, 2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 18 ',
            duration: 'duration: 26 hrs 40 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: yes',
            link: 'https://www.cleartrip.com/trains/amp/12723'
        },
        {
            id: 2,
            img: img4,
            title: '22416 - Andhra Pradesh Express',
            desc: 'New Delhi to Vishakapatnam',
            time: '06:40 - 18:45',
            classes: '1A, 2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 21 ',
            duration: 'duration: 36 hrs 5 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/22416'
        },
        {
            id: 3,
            img: img3,
            title: '12724 - Andhra Pradesh Express',
            desc: 'New Delhi to Hyderabad Decan',
            time: '17:25 - 19:50',
            classes: '1A, 2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 16 ',
            duration: 'duration: 26 hrs 25 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: yes',
            link: 'https://www.cleartrip.com/trains/amp/12724'
        },
        {
            id: 4,
            img: img6,
            title: '12707 - Andhra Pradesh Sampark Kranti',
            desc: 'Tirupati to H Nizamuddin',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/12707'
        },
        {
            id: 1,
            img: img5,
            title: '15609 - Abadh Assam Express',
            desc: 'New Tinsukia Junction to Darbhanga Junction',
            time: '10:40 - 19:40',
            classes: '2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 95 ',
            duration: 'duration: 33 hrs 0 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: yes',
            link: 'https://www.cleartrip.com/trains/amp/15609'
        },
        {
            id: 2,
            img: img2,
            title: '15909 - Abadh Assam Express',
            desc: 'New Tinsukia Junction to Darbhanga Junction',
            time: '10:40 - 19:40',
            classes: '2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 96 ',
            duration: 'duration: 33 hrs 0 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/15909'
        },
        {
            id: 3,
            img: img5,
            title: '18242 - Abkp Durg Passenger E',
            desc: 'Ambikapur to Durg',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, T, W, Th, F, Sa, S',
            stops: 'stops: 32 ',
            duration: 'duration: 11 hrs 55 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/18242'
        },
        {
            id: 4,
            img: img2,
            title: '11266 - Ambikapur Jbp Express',
            desc: 'Ambikapur to Jabalpur',
            time: '06:15 - 14:55',
            classes: '2S',
            days: 'M, W, F',
            stops: 'stops: 14 ',
            duration: 'duration: 8 hrs 40 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/11266'
        },
        {
            id: 1,
            img: img1,
            title: '54703 - Abohar Ju Passenger',
            desc: 'Abohar to Jodhpur Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/54703'
        },
        {
            id: 2,
            img: img4,
            title: '07509 - Adb Qln Special',
            desc: 'Adilabad to Kollam Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/07509'
        },
        {
            id: 3,
            img: img6,
            title: '09427 - Adi Ald Special',
            desc: 'Adi Junction - Allahabad Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/09427'
        },
        {
            id: 4,
            img: img4,
            title: '09018 - Adi Bct Ac Special',
            desc: 'Adi Junction - Mumbai Central',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/09018'
        },
        {
            id: 5,
            img: img6,
            title: '14804 - Adi Bgkt Express',
            desc: 'Ahmedabad Junction - Bhagat Ki Kothi',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/14804'
        },
        {
            id: 6,
            img: img3,
            title: '04804 - Adi Bgkt Special',
            desc: 'Ahmedabad Junction - Bhagat Ki Kothi',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/04804'
        },
        {
            id: 7,
            img: img4,
            title: '09421 - Ahmedabad Barmer Ac Special',
            desc: 'Ahmedabad Junction - Barmer',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/09421'
        },
        {
            id: 8,
            img: img3,
            title: '19130 - Adi Brc Intercity',
            desc: 'Ahmedabad Junction to Vadodara Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/19130'
        },
        {
            id: 8,
            img: img3,
            title: '02713 - Adi Bza Superfast Special',
            desc: 'Ahmedabad Junction to Vijayawada Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/02713'
        },
        {
            id: 8,
            img: img4,
            title: '19420 - Ahmedabad Chennai Express',
            desc: 'Ahmedabad Junction to Chennai Central',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/19420'
        },
        {
            id: 8,
            img: img4,
            title: '09417 - Ahmedabad Dee Premium',
            desc: 'Ahmedabad Junction to Delhi S Rohilla',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/09417'
        },
        {
            id: 8,
            img: img3,
            title: '12931 - Ahmedabad Double Deck',
            desc: 'Mumbai Central to Ahmedabad Junction',
            time: '17:25 - 19:50',
            classes: '2A, 3A, SL',
            days: 'M, W, F',
            stops: 'stops: 20 ',
            duration: 'duration: 36 hrs 15 mins',
            type: 'type: Mail / Express',
            pantry: 'pantry: no',
            link: 'https://www.cleartrip.com/trains/amp/12931'
        }

    ]
}
export default data;